name: Code Quality Check

on:
  push:
    branches: [ main, master, dev ]
  pull_request:
    branches: [ main, master ]

jobs:
  quality-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pylint black
        pip install -r requirements.txt
    
    - name: Check code formatting with Black
      run: black --check . || true
    
    - name: Lint with Flake8
      run: flake8 . --max-line-length=127 --ignore=E501,W503 || true
    
    - name: Run Pylint
      run: pylint **/*.py --exit-zero || true
    
    - name: Check for security issues
      run: |
        pip install bandit safety
        bandit -r . -f json -o bandit-report.json || true
        safety check || true
      continue-on-error: true
    
    - name: Upload reports
      uses: actions/upload-artifact@v3
      with:
        name: quality-reports
        path: |
          bandit-report.json
      if: always()
